// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ccany/ent/appconfig"
	"ccany/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppConfigUpdate is the builder for updating AppConfig entities.
type AppConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AppConfigMutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (acu *AppConfigUpdate) Where(ps ...predicate.AppConfig) *AppConfigUpdate {
	acu.mutation.Where(ps...)
	return acu
}

// SetKey sets the "key" field.
func (acu *AppConfigUpdate) SetKey(s string) *AppConfigUpdate {
	acu.mutation.SetKey(s)
	return acu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableKey(s *string) *AppConfigUpdate {
	if s != nil {
		acu.SetKey(*s)
	}
	return acu
}

// SetValue sets the "value" field.
func (acu *AppConfigUpdate) SetValue(s string) *AppConfigUpdate {
	acu.mutation.SetValue(s)
	return acu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableValue(s *string) *AppConfigUpdate {
	if s != nil {
		acu.SetValue(*s)
	}
	return acu
}

// SetCategory sets the "category" field.
func (acu *AppConfigUpdate) SetCategory(s string) *AppConfigUpdate {
	acu.mutation.SetCategory(s)
	return acu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableCategory(s *string) *AppConfigUpdate {
	if s != nil {
		acu.SetCategory(*s)
	}
	return acu
}

// SetType sets the "type" field.
func (acu *AppConfigUpdate) SetType(s string) *AppConfigUpdate {
	acu.mutation.SetType(s)
	return acu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableType(s *string) *AppConfigUpdate {
	if s != nil {
		acu.SetType(*s)
	}
	return acu
}

// SetDescription sets the "description" field.
func (acu *AppConfigUpdate) SetDescription(s string) *AppConfigUpdate {
	acu.mutation.SetDescription(s)
	return acu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableDescription(s *string) *AppConfigUpdate {
	if s != nil {
		acu.SetDescription(*s)
	}
	return acu
}

// ClearDescription clears the value of the "description" field.
func (acu *AppConfigUpdate) ClearDescription() *AppConfigUpdate {
	acu.mutation.ClearDescription()
	return acu
}

// SetIsEncrypted sets the "is_encrypted" field.
func (acu *AppConfigUpdate) SetIsEncrypted(b bool) *AppConfigUpdate {
	acu.mutation.SetIsEncrypted(b)
	return acu
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableIsEncrypted(b *bool) *AppConfigUpdate {
	if b != nil {
		acu.SetIsEncrypted(*b)
	}
	return acu
}

// SetIsRequired sets the "is_required" field.
func (acu *AppConfigUpdate) SetIsRequired(b bool) *AppConfigUpdate {
	acu.mutation.SetIsRequired(b)
	return acu
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableIsRequired(b *bool) *AppConfigUpdate {
	if b != nil {
		acu.SetIsRequired(*b)
	}
	return acu
}

// SetDefaultValue sets the "default_value" field.
func (acu *AppConfigUpdate) SetDefaultValue(s string) *AppConfigUpdate {
	acu.mutation.SetDefaultValue(s)
	return acu
}

// SetNillableDefaultValue sets the "default_value" field if the given value is not nil.
func (acu *AppConfigUpdate) SetNillableDefaultValue(s *string) *AppConfigUpdate {
	if s != nil {
		acu.SetDefaultValue(*s)
	}
	return acu
}

// ClearDefaultValue clears the value of the "default_value" field.
func (acu *AppConfigUpdate) ClearDefaultValue() *AppConfigUpdate {
	acu.mutation.ClearDefaultValue()
	return acu
}

// SetUpdatedAt sets the "updated_at" field.
func (acu *AppConfigUpdate) SetUpdatedAt(t time.Time) *AppConfigUpdate {
	acu.mutation.SetUpdatedAt(t)
	return acu
}

// Mutation returns the AppConfigMutation object of the builder.
func (acu *AppConfigUpdate) Mutation() *AppConfigMutation {
	return acu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (acu *AppConfigUpdate) Save(ctx context.Context) (int, error) {
	acu.defaults()
	return withHooks(ctx, acu.sqlSave, acu.mutation, acu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (acu *AppConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := acu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (acu *AppConfigUpdate) Exec(ctx context.Context) error {
	_, err := acu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acu *AppConfigUpdate) ExecX(ctx context.Context) {
	if err := acu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (acu *AppConfigUpdate) defaults() {
	if _, ok := acu.mutation.UpdatedAt(); !ok {
		v := appconfig.UpdateDefaultUpdatedAt()
		acu.mutation.SetUpdatedAt(v)
	}
}

func (acu *AppConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeString))
	if ps := acu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := acu.mutation.Key(); ok {
		_spec.SetField(appconfig.FieldKey, field.TypeString, value)
	}
	if value, ok := acu.mutation.Value(); ok {
		_spec.SetField(appconfig.FieldValue, field.TypeString, value)
	}
	if value, ok := acu.mutation.Category(); ok {
		_spec.SetField(appconfig.FieldCategory, field.TypeString, value)
	}
	if value, ok := acu.mutation.GetType(); ok {
		_spec.SetField(appconfig.FieldType, field.TypeString, value)
	}
	if value, ok := acu.mutation.Description(); ok {
		_spec.SetField(appconfig.FieldDescription, field.TypeString, value)
	}
	if acu.mutation.DescriptionCleared() {
		_spec.ClearField(appconfig.FieldDescription, field.TypeString)
	}
	if value, ok := acu.mutation.IsEncrypted(); ok {
		_spec.SetField(appconfig.FieldIsEncrypted, field.TypeBool, value)
	}
	if value, ok := acu.mutation.IsRequired(); ok {
		_spec.SetField(appconfig.FieldIsRequired, field.TypeBool, value)
	}
	if value, ok := acu.mutation.DefaultValue(); ok {
		_spec.SetField(appconfig.FieldDefaultValue, field.TypeString, value)
	}
	if acu.mutation.DefaultValueCleared() {
		_spec.ClearField(appconfig.FieldDefaultValue, field.TypeString)
	}
	if value, ok := acu.mutation.UpdatedAt(); ok {
		_spec.SetField(appconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, acu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	acu.mutation.done = true
	return n, nil
}

// AppConfigUpdateOne is the builder for updating a single AppConfig entity.
type AppConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppConfigMutation
}

// SetKey sets the "key" field.
func (acuo *AppConfigUpdateOne) SetKey(s string) *AppConfigUpdateOne {
	acuo.mutation.SetKey(s)
	return acuo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableKey(s *string) *AppConfigUpdateOne {
	if s != nil {
		acuo.SetKey(*s)
	}
	return acuo
}

// SetValue sets the "value" field.
func (acuo *AppConfigUpdateOne) SetValue(s string) *AppConfigUpdateOne {
	acuo.mutation.SetValue(s)
	return acuo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableValue(s *string) *AppConfigUpdateOne {
	if s != nil {
		acuo.SetValue(*s)
	}
	return acuo
}

// SetCategory sets the "category" field.
func (acuo *AppConfigUpdateOne) SetCategory(s string) *AppConfigUpdateOne {
	acuo.mutation.SetCategory(s)
	return acuo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableCategory(s *string) *AppConfigUpdateOne {
	if s != nil {
		acuo.SetCategory(*s)
	}
	return acuo
}

// SetType sets the "type" field.
func (acuo *AppConfigUpdateOne) SetType(s string) *AppConfigUpdateOne {
	acuo.mutation.SetType(s)
	return acuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableType(s *string) *AppConfigUpdateOne {
	if s != nil {
		acuo.SetType(*s)
	}
	return acuo
}

// SetDescription sets the "description" field.
func (acuo *AppConfigUpdateOne) SetDescription(s string) *AppConfigUpdateOne {
	acuo.mutation.SetDescription(s)
	return acuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableDescription(s *string) *AppConfigUpdateOne {
	if s != nil {
		acuo.SetDescription(*s)
	}
	return acuo
}

// ClearDescription clears the value of the "description" field.
func (acuo *AppConfigUpdateOne) ClearDescription() *AppConfigUpdateOne {
	acuo.mutation.ClearDescription()
	return acuo
}

// SetIsEncrypted sets the "is_encrypted" field.
func (acuo *AppConfigUpdateOne) SetIsEncrypted(b bool) *AppConfigUpdateOne {
	acuo.mutation.SetIsEncrypted(b)
	return acuo
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableIsEncrypted(b *bool) *AppConfigUpdateOne {
	if b != nil {
		acuo.SetIsEncrypted(*b)
	}
	return acuo
}

// SetIsRequired sets the "is_required" field.
func (acuo *AppConfigUpdateOne) SetIsRequired(b bool) *AppConfigUpdateOne {
	acuo.mutation.SetIsRequired(b)
	return acuo
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableIsRequired(b *bool) *AppConfigUpdateOne {
	if b != nil {
		acuo.SetIsRequired(*b)
	}
	return acuo
}

// SetDefaultValue sets the "default_value" field.
func (acuo *AppConfigUpdateOne) SetDefaultValue(s string) *AppConfigUpdateOne {
	acuo.mutation.SetDefaultValue(s)
	return acuo
}

// SetNillableDefaultValue sets the "default_value" field if the given value is not nil.
func (acuo *AppConfigUpdateOne) SetNillableDefaultValue(s *string) *AppConfigUpdateOne {
	if s != nil {
		acuo.SetDefaultValue(*s)
	}
	return acuo
}

// ClearDefaultValue clears the value of the "default_value" field.
func (acuo *AppConfigUpdateOne) ClearDefaultValue() *AppConfigUpdateOne {
	acuo.mutation.ClearDefaultValue()
	return acuo
}

// SetUpdatedAt sets the "updated_at" field.
func (acuo *AppConfigUpdateOne) SetUpdatedAt(t time.Time) *AppConfigUpdateOne {
	acuo.mutation.SetUpdatedAt(t)
	return acuo
}

// Mutation returns the AppConfigMutation object of the builder.
func (acuo *AppConfigUpdateOne) Mutation() *AppConfigMutation {
	return acuo.mutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (acuo *AppConfigUpdateOne) Where(ps ...predicate.AppConfig) *AppConfigUpdateOne {
	acuo.mutation.Where(ps...)
	return acuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (acuo *AppConfigUpdateOne) Select(field string, fields ...string) *AppConfigUpdateOne {
	acuo.fields = append([]string{field}, fields...)
	return acuo
}

// Save executes the query and returns the updated AppConfig entity.
func (acuo *AppConfigUpdateOne) Save(ctx context.Context) (*AppConfig, error) {
	acuo.defaults()
	return withHooks(ctx, acuo.sqlSave, acuo.mutation, acuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (acuo *AppConfigUpdateOne) SaveX(ctx context.Context) *AppConfig {
	node, err := acuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (acuo *AppConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := acuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acuo *AppConfigUpdateOne) ExecX(ctx context.Context) {
	if err := acuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (acuo *AppConfigUpdateOne) defaults() {
	if _, ok := acuo.mutation.UpdatedAt(); !ok {
		v := appconfig.UpdateDefaultUpdatedAt()
		acuo.mutation.SetUpdatedAt(v)
	}
}

func (acuo *AppConfigUpdateOne) sqlSave(ctx context.Context) (_node *AppConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeString))
	id, ok := acuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := acuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appconfig.FieldID)
		for _, f := range fields {
			if !appconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := acuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := acuo.mutation.Key(); ok {
		_spec.SetField(appconfig.FieldKey, field.TypeString, value)
	}
	if value, ok := acuo.mutation.Value(); ok {
		_spec.SetField(appconfig.FieldValue, field.TypeString, value)
	}
	if value, ok := acuo.mutation.Category(); ok {
		_spec.SetField(appconfig.FieldCategory, field.TypeString, value)
	}
	if value, ok := acuo.mutation.GetType(); ok {
		_spec.SetField(appconfig.FieldType, field.TypeString, value)
	}
	if value, ok := acuo.mutation.Description(); ok {
		_spec.SetField(appconfig.FieldDescription, field.TypeString, value)
	}
	if acuo.mutation.DescriptionCleared() {
		_spec.ClearField(appconfig.FieldDescription, field.TypeString)
	}
	if value, ok := acuo.mutation.IsEncrypted(); ok {
		_spec.SetField(appconfig.FieldIsEncrypted, field.TypeBool, value)
	}
	if value, ok := acuo.mutation.IsRequired(); ok {
		_spec.SetField(appconfig.FieldIsRequired, field.TypeBool, value)
	}
	if value, ok := acuo.mutation.DefaultValue(); ok {
		_spec.SetField(appconfig.FieldDefaultValue, field.TypeString, value)
	}
	if acuo.mutation.DefaultValueCleared() {
		_spec.ClearField(appconfig.FieldDefaultValue, field.TypeString)
	}
	if value, ok := acuo.mutation.UpdatedAt(); ok {
		_spec.SetField(appconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AppConfig{config: acuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, acuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	acuo.mutation.done = true
	return _node, nil
}
