// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ccany/ent/predicate"
	"ccany/ent/requestlog"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestLogQuery is the builder for querying RequestLog entities.
type RequestLogQuery struct {
	config
	ctx        *QueryContext
	order      []requestlog.OrderOption
	inters     []Interceptor
	predicates []predicate.RequestLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RequestLogQuery builder.
func (rlq *RequestLogQuery) Where(ps ...predicate.RequestLog) *RequestLogQuery {
	rlq.predicates = append(rlq.predicates, ps...)
	return rlq
}

// Limit the number of records to be returned by this query.
func (rlq *RequestLogQuery) Limit(limit int) *RequestLogQuery {
	rlq.ctx.Limit = &limit
	return rlq
}

// Offset to start from.
func (rlq *RequestLogQuery) Offset(offset int) *RequestLogQuery {
	rlq.ctx.Offset = &offset
	return rlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rlq *RequestLogQuery) Unique(unique bool) *RequestLogQuery {
	rlq.ctx.Unique = &unique
	return rlq
}

// Order specifies how the records should be ordered.
func (rlq *RequestLogQuery) Order(o ...requestlog.OrderOption) *RequestLogQuery {
	rlq.order = append(rlq.order, o...)
	return rlq
}

// First returns the first RequestLog entity from the query.
// Returns a *NotFoundError when no RequestLog was found.
func (rlq *RequestLogQuery) First(ctx context.Context) (*RequestLog, error) {
	nodes, err := rlq.Limit(1).All(setContextOp(ctx, rlq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{requestlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rlq *RequestLogQuery) FirstX(ctx context.Context) *RequestLog {
	node, err := rlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RequestLog ID from the query.
// Returns a *NotFoundError when no RequestLog ID was found.
func (rlq *RequestLogQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rlq.Limit(1).IDs(setContextOp(ctx, rlq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{requestlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rlq *RequestLogQuery) FirstIDX(ctx context.Context) string {
	id, err := rlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RequestLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RequestLog entity is found.
// Returns a *NotFoundError when no RequestLog entities are found.
func (rlq *RequestLogQuery) Only(ctx context.Context) (*RequestLog, error) {
	nodes, err := rlq.Limit(2).All(setContextOp(ctx, rlq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{requestlog.Label}
	default:
		return nil, &NotSingularError{requestlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rlq *RequestLogQuery) OnlyX(ctx context.Context) *RequestLog {
	node, err := rlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RequestLog ID in the query.
// Returns a *NotSingularError when more than one RequestLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (rlq *RequestLogQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rlq.Limit(2).IDs(setContextOp(ctx, rlq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{requestlog.Label}
	default:
		err = &NotSingularError{requestlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rlq *RequestLogQuery) OnlyIDX(ctx context.Context) string {
	id, err := rlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RequestLogs.
func (rlq *RequestLogQuery) All(ctx context.Context) ([]*RequestLog, error) {
	ctx = setContextOp(ctx, rlq.ctx, ent.OpQueryAll)
	if err := rlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RequestLog, *RequestLogQuery]()
	return withInterceptors[[]*RequestLog](ctx, rlq, qr, rlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rlq *RequestLogQuery) AllX(ctx context.Context) []*RequestLog {
	nodes, err := rlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RequestLog IDs.
func (rlq *RequestLogQuery) IDs(ctx context.Context) (ids []string, err error) {
	if rlq.ctx.Unique == nil && rlq.path != nil {
		rlq.Unique(true)
	}
	ctx = setContextOp(ctx, rlq.ctx, ent.OpQueryIDs)
	if err = rlq.Select(requestlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rlq *RequestLogQuery) IDsX(ctx context.Context) []string {
	ids, err := rlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rlq *RequestLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rlq.ctx, ent.OpQueryCount)
	if err := rlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rlq, querierCount[*RequestLogQuery](), rlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rlq *RequestLogQuery) CountX(ctx context.Context) int {
	count, err := rlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rlq *RequestLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rlq.ctx, ent.OpQueryExist)
	switch _, err := rlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rlq *RequestLogQuery) ExistX(ctx context.Context) bool {
	exist, err := rlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RequestLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rlq *RequestLogQuery) Clone() *RequestLogQuery {
	if rlq == nil {
		return nil
	}
	return &RequestLogQuery{
		config:     rlq.config,
		ctx:        rlq.ctx.Clone(),
		order:      append([]requestlog.OrderOption{}, rlq.order...),
		inters:     append([]Interceptor{}, rlq.inters...),
		predicates: append([]predicate.RequestLog{}, rlq.predicates...),
		// clone intermediate query.
		sql:  rlq.sql.Clone(),
		path: rlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ClaudeModel string `json:"claude_model,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RequestLog.Query().
//		GroupBy(requestlog.FieldClaudeModel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rlq *RequestLogQuery) GroupBy(field string, fields ...string) *RequestLogGroupBy {
	rlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RequestLogGroupBy{build: rlq}
	grbuild.flds = &rlq.ctx.Fields
	grbuild.label = requestlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ClaudeModel string `json:"claude_model,omitempty"`
//	}
//
//	client.RequestLog.Query().
//		Select(requestlog.FieldClaudeModel).
//		Scan(ctx, &v)
func (rlq *RequestLogQuery) Select(fields ...string) *RequestLogSelect {
	rlq.ctx.Fields = append(rlq.ctx.Fields, fields...)
	sbuild := &RequestLogSelect{RequestLogQuery: rlq}
	sbuild.label = requestlog.Label
	sbuild.flds, sbuild.scan = &rlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RequestLogSelect configured with the given aggregations.
func (rlq *RequestLogQuery) Aggregate(fns ...AggregateFunc) *RequestLogSelect {
	return rlq.Select().Aggregate(fns...)
}

func (rlq *RequestLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rlq); err != nil {
				return err
			}
		}
	}
	for _, f := range rlq.ctx.Fields {
		if !requestlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rlq.path != nil {
		prev, err := rlq.path(ctx)
		if err != nil {
			return err
		}
		rlq.sql = prev
	}
	return nil
}

func (rlq *RequestLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RequestLog, error) {
	var (
		nodes = []*RequestLog{}
		_spec = rlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RequestLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RequestLog{config: rlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rlq *RequestLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rlq.querySpec()
	_spec.Node.Columns = rlq.ctx.Fields
	if len(rlq.ctx.Fields) > 0 {
		_spec.Unique = rlq.ctx.Unique != nil && *rlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rlq.driver, _spec)
}

func (rlq *RequestLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeString))
	_spec.From = rlq.sql
	if unique := rlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rlq.path != nil {
		_spec.Unique = true
	}
	if fields := rlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestlog.FieldID)
		for i := range fields {
			if fields[i] != requestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rlq *RequestLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rlq.driver.Dialect())
	t1 := builder.Table(requestlog.Table)
	columns := rlq.ctx.Fields
	if len(columns) == 0 {
		columns = requestlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rlq.sql != nil {
		selector = rlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rlq.ctx.Unique != nil && *rlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rlq.predicates {
		p(selector)
	}
	for _, p := range rlq.order {
		p(selector)
	}
	if offset := rlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RequestLogGroupBy is the group-by builder for RequestLog entities.
type RequestLogGroupBy struct {
	selector
	build *RequestLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rlgb *RequestLogGroupBy) Aggregate(fns ...AggregateFunc) *RequestLogGroupBy {
	rlgb.fns = append(rlgb.fns, fns...)
	return rlgb
}

// Scan applies the selector query and scans the result into the given value.
func (rlgb *RequestLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rlgb.build.ctx, ent.OpQueryGroupBy)
	if err := rlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RequestLogQuery, *RequestLogGroupBy](ctx, rlgb.build, rlgb, rlgb.build.inters, v)
}

func (rlgb *RequestLogGroupBy) sqlScan(ctx context.Context, root *RequestLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rlgb.fns))
	for _, fn := range rlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rlgb.flds)+len(rlgb.fns))
		for _, f := range *rlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RequestLogSelect is the builder for selecting fields of RequestLog entities.
type RequestLogSelect struct {
	*RequestLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rls *RequestLogSelect) Aggregate(fns ...AggregateFunc) *RequestLogSelect {
	rls.fns = append(rls.fns, fns...)
	return rls
}

// Scan applies the selector query and scans the result into the given value.
func (rls *RequestLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rls.ctx, ent.OpQuerySelect)
	if err := rls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RequestLogQuery, *RequestLogSelect](ctx, rls.RequestLogQuery, rls, rls.inters, v)
}

func (rls *RequestLogSelect) sqlScan(ctx context.Context, root *RequestLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rls.fns))
	for _, fn := range rls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
