// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppConfig is the predicate function for appconfig builders.
type AppConfig func(*sql.Selector)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// RequestLog is the predicate function for requestlog builders.
type RequestLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
